#!/usr/bin/env bash
# ASCEND-@@SITELABEL@@ — launch Claude Code ON @@SITE@@ (@@KINDDESC@@)
# from this computer. Generated by ASCEND custom/setup-custom.sh; the agent
# runs on the remote host, reached over the multiplexed '@@REMOTE@@' ssh alias.
#
#   ascend-@@SITE@@                    # start in the site's projects dir
#   ascend-@@SITE@@ -d <remote-path>   # start in a specific project (remote path)
#   ascend-@@SITE@@ --tmux             # run inside tmux on the remote (survives disconnects)
#   ascend-@@SITE@@ --check            # test link + claude (+ scheduler/GPU) and exit
#
# Needs the "@@REMOTE@@" ssh alias (ControlMaster + key auth = passwordless).
# Written for macOS bash 3.2.
set -Eeuo pipefail

SRC="$0"
while [ -h "$SRC" ]; do
  D="$(cd "$(dirname "$SRC")" && pwd)"
  SRC="$(readlink "$SRC")"
  case "$SRC" in /*) ;; *) SRC="$D/$SRC" ;; esac
done
BUNDLE="$(cd "$(dirname "$SRC")/.." && pwd)"
REMOTE="${ASCEND_@@SITEVAR@@_REMOTE:-@@REMOTE@@}"
KIND="@@KIND@@"   # slurm | gpu | cpu
WORKDIR="${ASCEND_@@SITEVAR@@_PROJECT_DIR:-}"
CHECK=0
TMUX=0
ARGS=()

while [ $# -gt 0 ]; do
  case "$1" in
    -d) WORKDIR="$2"; shift 2 ;;
    --check) CHECK=1; shift ;;
    --tmux) TMUX=1; shift ;;
    -h|--help) sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    --) shift; while [ $# -gt 0 ]; do ARGS[${#ARGS[@]}]="$1"; shift; done ;;
    *) ARGS[${#ARGS[@]}]="$1"; shift ;;
  esac
done

b()  { printf '\033[38;5;31m%s\033[0m\n' "$*"; }
dim(){ printf '\033[38;5;245m%s\033[0m\n' "$*"; }

if ! ssh -o BatchMode=yes -o ConnectTimeout=10 "$REMOTE" true 2>/dev/null; then
  echo "cannot reach '$REMOTE' non-interactively." >&2
  echo "  Check the alias and key:  ssh $REMOTE true   (should return with no password)" >&2
  echo "  If it asks for a password, run:  ssh-copy-id $REMOTE" >&2
  echo "  If the site needs Duo/password each time, warm the link once:  ssh $REMOTE true" >&2
  exit 1
fi

# Resolve the remote working dir if not given (uses the remote's $ASCEND_SCRATCH).
if [ -z "$WORKDIR" ]; then
  WORKDIR="$(ssh "$REMOTE" 'echo "${ASCEND_SCRATCH:-$HOME/agents}/projects-@@SITE@@"' 2>/dev/null)"
  [ -n "$WORKDIR" ] || WORKDIR="\$HOME/agents/projects-@@SITE@@"
fi

if [ "$CHECK" = "1" ]; then
  # Run through a LOGIN shell so ~/.local/bin (claude) and ~/bin are on PATH.
  case "$KIND" in
    slurm) EXTRA='sinfo -h -o "%P %a %D %t" 2>/dev/null | head -5 || echo "sinfo: none"; squeue -h -u "$USER" 2>/dev/null | wc -l | sed "s/^/your queued jobs: /"' ;;
    gpu)   EXTRA='nvidia-smi --query-gpu=name,memory.total,memory.used --format=csv,noheader 2>/dev/null || echo "nvidia-smi: none"' ;;
    *)     EXTRA='uptime' ;;
  esac
  RC="hostname; grep -h PRETTY /etc/os-release 2>/dev/null; command -v claude >/dev/null && claude --version || echo 'claude: NOT on PATH'; $EXTRA; curl -sI --max-time 5 https://api.anthropic.com >/dev/null && echo 'anthropic api: reachable' || echo 'anthropic api: UNREACHABLE'; command -v tmux >/dev/null && echo 'tmux: present' || echo 'tmux: absent'; echo OK"
  ssh "$REMOTE" "bash -lc $(printf '%q' "$RC")"
  exit 0
fi

printf '\033]0;ASCEND-@@SITELABEL@@ — %s\007' "${WORKDIR##*/}"
echo
b '    ▄▀█ █▀ █▀▀ █▀▀ █▄░█ █▀▄'
b '    █▀█ ▄█ █▄▄ ██▄ █░▀█ █▄▀'
echo
printf '    \033[1mASCEND-@@SITELABEL@@\033[0m\n'
dim "    Autonomous Scientific Computing Engine and Novel Discovery"
echo
dim "    site     @@SITE@@ (@@KINDDESC@@) via ssh alias '@@REMOTE@@'"
dim "    workdir  $WORKDIR  (on the remote)"
case "$KIND" in
  slurm)
    dim "    agent    Claude Code runs on the LOGIN NODE — scheduling + env builds only"
    dim "    compute  everything heavy goes through Slurm (hpcrun / sbatch), never the login node"
    ;;
  gpu)
    dim "    agent    Claude Code runs ON the box — GPU is local, NO scheduler"
    dim "    share    check 'nvidia-smi' before heavy runs; the GPU may be shared"
    ;;
  *)
    dim "    agent    Claude Code runs ON the box — no scheduler; run in place"
    ;;
esac
dim "    tools    ~/bin: hpcrun · hpcrepro · fetch-paper"
echo

# Seed AGENTS.md on the remote if this project doesn't have one.
if ! ssh "$REMOTE" "test -f '$WORKDIR/AGENTS.md' || test -f '$WORKDIR/CLAUDE.md'"; then
  ssh "$REMOTE" "mkdir -p '$WORKDIR'"
  if [ -f "$BUNDLE/AGENTS.md" ]; then
    ssh "$REMOTE" "cat > '$WORKDIR/AGENTS.md'" < "$BUNDLE/AGENTS.md"
    dim "    (added AGENTS.md to this project on the remote from the site template)"
  fi
fi

# Ship the remote command base64-encoded so no quoting layer mangles it; run
# via a LOGIN shell so ~/.local/bin (claude) and any token in ~/.bashrc load.
CLAUDE_ARGS=""
[ ${#ARGS[@]} -gt 0 ] && CLAUDE_ARGS=" ${ARGS[*]}"
INNER="cd '$WORKDIR' && exec claude$CLAUDE_ARGS"
if [ "$TMUX" = "1" ]; then
  PAYLOAD="if command -v tmux >/dev/null 2>&1; then exec tmux new -A -s ascend-@@SITE@@ -c '$WORKDIR' \"bash -lc \\\"$INNER\\\"\"; else $INNER; fi"
else
  PAYLOAD="$INNER"
fi
B64=$(printf '%s' "$PAYLOAD" | LC_ALL=C base64 | tr -d '\n')
exec ssh -t "$REMOTE" "bash -lc 'eval \"\$(printf %s $B64 | base64 -d)\"'"
