#!/usr/bin/env bash
# ASCEND-@@SITELABEL@@ — the ASCEND front door for @@SITE@@ (@@KINDDESC@@),
# running on THIS computer. Generated by ASCEND custom/setup-custom.sh.
#
# The agent (Claude Code or Codex) runs locally with your computer's network
# and login; site work is routed per-command through the multiplexed ssh
# alias '@@REMOTE@@'. On a Slurm site the login node is used ONLY for
# scheduling and environment builds — real compute goes through sbatch.
#
#   ascend-@@SITE@@                    # start in the site's local projects dir
#   ascend-@@SITE@@ -d <local-path>    # start in a specific project (local path)
#   ascend-@@SITE@@ --check            # test the link + remote tools and exit
#   ascend-@@SITE@@ --codex            # skip the question: use Codex (OpenAI)
#   ascend-@@SITE@@ --claude           # skip the question: use Claude Code
#
# Every launch shows the ASCEND banner, then asks which agent to use
# (1: Claude Code, 2: Codex). If the site needs a password/Duo per
# connection, warm the link once in another terminal:  ssh @@REMOTE@@
# Written for macOS bash 3.2.
set -Eeuo pipefail

SRC="$0"
while [ -h "$SRC" ]; do
  D="$(cd "$(dirname "$SRC")" && pwd)"
  SRC="$(readlink "$SRC")"
  case "$SRC" in /*) ;; *) SRC="$D/$SRC" ;; esac
done
BUNDLE="$(cd "$(dirname "$SRC")/.." && pwd)"
REMOTE="${ASCEND_@@SITEVAR@@_REMOTE:-@@REMOTE@@}"
KIND="@@KIND@@"   # slurm | gpu | cpu
WORKDIR="${ASCEND_@@SITEVAR@@_PROJECT_DIR:-$HOME/agents/custom/projects-@@SITE@@}"
if [ -f "$PWD/AGENTS.md" ] || [ -f "$PWD/CLAUDE.md" ]; then WORKDIR="$PWD"; fi
CHECK=0
AGENT_CHOICE=""
ARGS=()

while [ $# -gt 0 ]; do
  case "$1" in
    -d) WORKDIR="$2"; shift 2 ;;
    --check) CHECK=1; shift ;;
    --claude) AGENT_CHOICE="claude"; shift ;;
    --codex) AGENT_CHOICE="codex"; shift ;;
    -h|--help) sed -n '2,19p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    --) shift; while [ $# -gt 0 ]; do ARGS[${#ARGS[@]}]="$1"; shift; done ;;
    *) ARGS[${#ARGS[@]}]="$1"; shift ;;
  esac
done

b()  { printf '\033[38;5;31m%s\033[0m\n' "$*"; }
dim(){ printf '\033[38;5;245m%s\033[0m\n' "$*"; }

# Is the multiplexed link usable without prompting? (warm socket OR key auth)
link_up() { ssh -o BatchMode=yes -o ConnectTimeout=10 "$REMOTE" true 2>/dev/null; }

if [ "$CHECK" = "1" ]; then
  echo "Checking the '$REMOTE' link (no interactive prompts will be issued)..."
  if ! link_up; then
    echo "  link: COLD / unreachable non-interactively."
    echo "  Warm it in another terminal:  ssh $REMOTE   (log in once; multiplexing keeps it warm)"
    echo "  For passwordless use:         ssh-copy-id $REMOTE"
    echo "  Then re-run:  ascend-@@SITE@@ --check"
    exit 1
  fi
  echo "  link: UP"
  printf '  remote:  '
  ssh "$REMOTE" 'hostname' 2>/dev/null || echo "hostname failed"
  case "$KIND" in
    slurm)
      printf '  slurm:   '
      ssh "$REMOTE" 'sinfo --version 2>/dev/null || echo "sinfo failed"'
      printf '  queue:   '
      ssh "$REMOTE" 'squeue -h -u "$USER" 2>/dev/null | wc -l | sed "s/$/ job(s) queued\/running/"' ;;
    gpu)
      printf '  gpu:     '
      ssh "$REMOTE" 'nvidia-smi --query-gpu=name,memory.total,memory.used --format=csv,noheader 2>/dev/null || echo "nvidia-smi failed"' ;;
    *)
      printf '  load:    '
      ssh "$REMOTE" 'uptime' 2>/dev/null || echo "uptime failed" ;;
  esac
  printf '  tools:   '
  ssh "$REMOTE" 'ls ~/bin/hpcrun ~/bin/hpcrepro 2>/dev/null | tr "\n" " "; echo' \
    || echo "(hpcrun/hpcrepro not found in ~/bin — re-run custom/deploy-custom.sh)"
  exit 0
fi

if [ ! -d "$WORKDIR" ]; then
  echo "creating workdir: $WORKDIR"
  mkdir -p "$WORKDIR" || { echo "cannot create workdir: $WORKDIR" >&2; exit 1; }
fi

printf '\033]0;ASCEND-@@SITELABEL@@ — %s\007' "${WORKDIR##*/}"
echo
b '    ▄▀█ █▀ █▀▀ █▀▀ █▄░█ █▀▄'
b '    █▀█ ▄█ █▄▄ ██▄ █░▀█ █▄▀'
echo
printf '    \033[1mASCEND-@@SITELABEL@@\033[0m\n'
dim "    Autonomous Scientific Computing Engine and Novel Discovery"
echo
dim "    site     @@SITE@@ (@@KINDDESC@@) via ssh alias '@@REMOTE@@'"
dim "    workdir  $WORKDIR  (on this computer)"
case "$KIND" in
  slurm)
    dim "    agent    runs HERE, on this computer — remote login node: scheduling + env builds ONLY"
    dim "    compute  everything heavy goes through Slurm (ssh $REMOTE 'hpcrun ...' / sbatch)"
    ;;
  gpu)
    dim "    agent    runs HERE, on this computer — remote GPU box has NO scheduler"
    dim "    share    check nvidia-smi over ssh before heavy runs; the GPU may be shared"
    ;;
  *)
    dim "    agent    runs HERE, on this computer — remote box has no scheduler; run in place"
    ;;
esac
dim "    remote   ssh $REMOTE '<cmd>'  ·  ~/bin there: hpcrun · hpcrepro · fetch-paper"
if link_up; then
  dim "    link     warm — $REMOTE commands run without prompts"
else
  dim "    link     COLD — warm it first in another terminal:  ssh $REMOTE"
fi
echo

# Pick the agent CLI (Claude Code default / Codex), remembered per site.
AGENTLIB="$HOME/.ascend/lib/agent-select.sh"
if [ -f "$AGENTLIB" ]; then
  . "$AGENTLIB"
else
  ASCEND_AGENT="${AGENT_CHOICE:-claude}"; case "$ASCEND_AGENT" in ask) ASCEND_AGENT=claude ;; esac
  ASCEND_AGENT_LABEL="Claude Code"; [ "$ASCEND_AGENT" = codex ] && ASCEND_AGENT_LABEL="Codex"
  agent_select() { :; }
  agent_ensure_local() { command -v "$ASCEND_AGENT" >/dev/null 2>&1 || { echo "$ASCEND_AGENT is not on PATH." >&2; exit 1; }; }
  agent_version_label() { printf '%s' "$ASCEND_AGENT_LABEL"; }
fi
agent_select @@SITE@@ "$AGENT_CHOICE"
agent_ensure_local
dim "    agent    $(agent_version_label)"
echo

# Seed the project with the site's standing instructions.
if [ ! -f "$WORKDIR/AGENTS.md" ] && [ ! -f "$WORKDIR/CLAUDE.md" ]; then
  if [ -f "$BUNDLE/AGENTS.md" ]; then
    cp "$BUNDLE/AGENTS.md" "$WORKDIR/AGENTS.md"
    dim "    (added AGENTS.md to this project from the site template)"
  fi
fi

cd "$WORKDIR"
exec "$ASCEND_AGENT" ${ARGS[@]+"${ARGS[@]}"}
